apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: cluster-upgrade-4-14
  namespace: demo-policy
spec:
  disabled: true
  description: tasks like admin acks and channel setting
  policies:
    - admin-acks-414
    - upgrade-cluster-channel-414
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: cluster-upgrade-4-14-placement
  namespace: demo-policy
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - local-cluster
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: cluster-upgrade-4-14-placement
  namespace: demo-policy
placementRef:
  name: cluster-upgrade-4-14-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: cluster-upgrade-4-14
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet
